on:
  push:
    branches:
      - master

env:
  ResourceGroup: letsencrypt-inttest
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@01aecccf739ca6ff86c0539fbc67a7a5007bbc81 # pin@v2 
    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Azure CLI ARM deployment
      uses: azure/CLI@v1
      with:
        inlineScript: |
          cd internal/deploy
          chmod +x deploy.sh
          ./deploy.sh $ResourceGroup
